### ISSUE TITLE
Many functions don't take an explicit browser

### ISSUE THREAD

**Issue by nwjsmith** [milankinen/cuic#15]
In the (excellent) documentation for browser management, one of the options mentioned is
> 1. Pass it directly to each function invocation
For many (most?) functions, it doesn't appear this is possible. Should this be removed from the documentation?

Thanks for cuic, it's really useful.

**Comment by milankinen** [comment]
Hi and thanks for the isue! And sorry that I have not responded this earlier, for some reason I haven't got any notification for this issue! 😞 

The browser is bound to the element retrieved from query functions (e.g. `c/find`) which allow you to explicitly bind the browser. When a node is received, it's bound to the browser that was being used during the query time and that can't be changed anymore. 

I admit this is a bit unclear and I'll add some comment about this to the documentation!
